export let ingredients = [
  {
    id: 0,
    name:  'помидоры',
    cost: 20,
    url: '../img/creator/ingredient-1.png',
    left: 0,
    top: 0,
    added: 0,
    initWeight: 40,
    limit: 3
  },
  {
    id: 1,
    name:  'грибы',
    cost: 10,
    url: '../img/creator/ingredient-2.png',
    left: 0,
    top: 0,
    added: 0,
    initWeight: 50,
    limit: 3
  },
  {
    id: 2,
    name:  'зелень',
    cost: 5,
    url: '../img/creator/ingredient-3.png',
    left: 0,
    top: 0,
    added: 0,
    initWeight: 5,
    limit: 5
  },
  {
    id: 3,
    name:  'сыр',
    cost: 12,
    url: '../img/creator/ingredient-4.png',
    left: 0,
    top: 0,
    added: 0,
    initWeight: 45,
    limit: 2
  },
  {
    id: 4,
    name:  'маслины',
    cost: 21,
    url: '../img/creator/ingredient-5.png',
    left: 0,
    top: 0,
    added: 0,
    initWeight: 20,
    limit: 12
  },
  {
    id: 5,
    name:  'лук',
    cost: 4,
    url: '../img/creator/ingredient-6.png',
    left: 0,
    top: 0,
    added: 0,
    initWeight: 15,
    limit: 15
  },
  {
    id: 6,
    cost: 16,
    name:  'салями',
    url: '../img/creator/ingredient-7.png',
    left: 0,
    top: 0,
    added: 0,
    initWeight: 50,
    limit: 2
  },
  {
    id: 7,
    name:  'перец',
    cost: 8,
    url: '../img/creator/ingredient-8.png',
    left: 0,
    top: 0,
    added: 0,
    initWeight: 23,
    limit: 5
  },
  {
    id: 8,
    name:  'ананасы',
    cost: 23,
    url: '../img/creator/ingredient-9.png',
    left: 0,
    top: 0,
    added: 0,
    initWeight: 30,
    limit: 1
  },
  {
    id: 9,
    name:  'перец сладкий',
    cost: 11,
    url: '../img/creator/ingredient-10.png',
    left: 0,
    top: 0,
    added: 0,
    initWeight: 20,
    limit: 3
  },
  {
    id: 10,
    name:  'рыба',
    cost: 19,
    url: '../img/creator/ingredient-11.png',
    left: 0,
    top: 0,
    added: 0,
    initWeight: 60,
    limit: 2
  },
  {
    id: 11,
    name:  'свинина',
    cost: 27,
    url: '../img/creator/ingredient-12.png',
    left: 0,
    top: 0,
    added: 0,
    initWeight: 60,
    limit: 2
  },
  {
    id: 12,
    name:  'курица',
    cost: 18,
    url: '../img/creator/ingredient-13.png',
    left: 0,
    top: 0,
    added: 0,
    initWeight: 50,
    limit: 2
  },
  {
    id: 13,
    name:  'кукуруза',
    cost: 7,
    url: '../img/creator/ingredient-14.png',
    left: 0,
    top: 0,
    added: 0,
    initWeight: 10,
    limit: 10
  },
  {
    id: 14,
    name:  'огурец',
    cost: 5,
    url: '../img/creator/ingredient-15.png',
    left: 0,
    top: 0,
    added: 0,
    initWeight: 20,
    limit: 5
  },
  {
    id: 15,
    name:  'ветчина',
    cost: 22,
    url: '../img/creator/ingredient-16.png',
    left: 0,
    top: 0,
    added: 0,
    initWeight: 40,
    limit: 2
  },
  {
    id: 16,
    name:  'острый перец',
    cost: 8,
    url: '../img/creator/ingredient-17.png',
    left: 0,
    top: 0,
    added: 0,
    initWeight: 20,
    limit: 3
  },
  {
    id: 17,
    name:  'листья салата',
    cost: 14,
    url: '../img/creator/ingredient-18.png',
    left: 0,
    top: 0,
    added: 0,
    initWeight: 10,
    limit: 15
  },
  {
    id: 18,
    name:  'морепродукты',
    cost: 30,
    url: '../img/creator/ingredient-19.png',
    left: 0,
    top: 0,
    added: 0,
    initWeight: 50,
    limit: 5
  },
  {
    id: 19,
    name:  'кетчуп',
    cost: 5,
    url: '../img/creator/ingredient-20.png',
    left: 0,
    top: 0,
    added: 0,
    initWeight: 20,
    limit: 2
  },
  {
    id: 20,
    name:  'горчица',
    cost: 5,
    url: '../img/creator/ingredient-21.png',
    left: 0,
    top: 0,
    added: 0,
    initWeight: 20,
    limit: 2
  },
  {
    id: 21,
    name:  'майонез',
    cost: 5,
    url: '../img/creator/ingredient-22.png',
    left: 0,
    top: 0,
    added: 0,
    initWeight: 20,
    limit: 2
  }
];
